name: CI

on:
 push:
   branches: ["main"]
   
iobs:
 my_build_job:
  run-on: ubunt-latest
  steps:
   -uses: actions/checkout@v3
   -name: npm install, test and build
    run:|
     npm install
     npm run build
   -name: Run a one-line script
    run: echo Hello, world!
     
   -name: Run JS file for test
    run: node script.js
